export type EstadoJuego = 
"ESPERANDO_COMPAÑERO" |
"TURNO_P1" |
"TURNO_P2" |
"VICTORIA_P1" |
"VICTORIA_P2" |
"EMPATE" |
"ABANDONADO" |
"VICTORIA_FINAL_P1" |
"VICTORIA_FINAL_P2"|
"CANCELADA"|
"REMATCH";